// src/RichContentBundle/Resources/js/components/BlockList.vue
<template>
  <div class="block-list">
    <Block v-for="block, i in sortedBlocks" :key="block.id" :block="block" :id="block.id" :position="i" :editorIndex="editorIndex" />
  </div>
</template>

<script>
 import Block from './Block';

 export default {
   props: ['editorIndex'],

   created() {
     /* const { store } = this.context;*/
     /* this.unsubscribe = store.subscribe(() => {*/
     /* this.forceUpdate();*/
     /* });*/
   },

   beforeDestroy() {
     /* this.unsubscribe();*/
   },

   components: {
     Block
   },

   computed: {
     sortedBlocks() {
       const order = this.$store.state.editors[this.editorIndex].order;
       let blocks = [];

       for (let i=0; i < order.length; i++) {
         let id = order[i][0];
         let block = this.$store.state.blocks[id];
         if (!block) {
           throw Error(`Unknown block ${id}`);
         }
         block.id = id;
         block.key = order[i][1];
         blocks.push(block);
       }

       return blocks;
     }
   }
 }
</script>

// src/RichContentBundle/Resources/js/components/BlockList.jsx
import React from 'react';

import Block from './Block';
import PropTypes from 'prop-types';

class BlockList extends React.Component {
  componentDidMount() {
    const { store } = this.context;
    this.unsubscribe = store.subscribe(() => {
      this.forceUpdate();
    });
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  render() {
    const components = [];
    const { store } = this.context;
    const state = store.getState();
    const order = state.editors[this.props.editorIndex].order;

    for (let i=0; i < order.length; i++) {
      let id = order[i][0];
      let key = order[i][1];

      if (!state.blocks[id]) {
        console.error(`Unknown block ${id}`, state);
      }
      let block = state.blocks[id];
      components.push(
        <Block key={key} block={block} id={id} position={i} />
      );
    }

    return (
      <div className="block-list">
        {components}
      </div>
    )
  }
}
BlockList.contextTypes = {
  store: PropTypes.object
};

export default BlockList;
