// src/RichContentBundle/Resources/js/components/Editor.jsx
import React from 'react';
import css from './editor.scss';
import BlockList from './BlockList';
import Toolbar from './Toolbar';
import 'whatwg-fetch';
import PropTypes from 'prop-types';

class Editor extends React.Component {
  getChildContext() {
    return {store: this.props.store};
  }

  render() {
    return (
      <div className={css.editor}>
        <Toolbar />
        <BlockList editorIndex={this.props.editorIndex}/>
      </div>
    );
  }
}
Editor.childContextTypes = {
  store: PropTypes.object
};

export default Editor;

// src/RichContentBundle/Resources/js/components/Editor.vue
<template>
  <div :class="css.editor">
    <Toolbar :editorIndex="editorIndex" />
    <BlockList :editorIndex="editorIndex" />
  </div>
</template>

<script>
 import BlockList from './BlockList';
 import Toolbar from './Toolbar';
 import css from './editor.scss';

 export default {
   props: ['editorIndex'],

   data() {
     return {
       css
     }
   },

   components: {
     BlockList,
     Toolbar
   }
 }
</script>
