// src/RichContentBundle/Resources/js/components/types/Text.vue
<template>
  <div>
    <p v-if="this.editing">
      {{this.value.content}}
    </p>
    <div v-else>
      <textarea v-model="content" rows="10" cols="80"></textarea>
      <a href="#" className="btn btn-info" :click.prevent="finishEdit">Done</a>
    </div>
  </div>
</template>

<script>
 export default {
   props: ['value', 'setBlockValue'],

   created() {
     this.content = this.value.content;
   },
   data() {
     return {
       editing: true,
     }
   },
   methods: {
     finishEdit(e) {
       this.setBlockValue({
         content: this.content
       });
     }
   }
 }
</script>

// src/RichContentBundle/Resources/js/components/Text.jsx
import React from 'react';

class Text extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      content: this.props.value.content
    };
  }

  onChange(e) {
    this.setState({
      content: e.currentTarget.value,
    });
  }

  finishEdit(e) {
    e.preventDefault();
    this.props.setBlockValue({
      content: this.state.content
    });
  }

  render() {
    if (!this.props.editing) {
      return <p>{this.props.value.content}</p>;
    }

    return (
      <div>
        <textarea value={this.state.content} onChange={this.onChange.bind(this)} rows="10" cols="80"></textarea>
        <a href="#" className="btn btn-info" onClick={this.finishEdit.bind(this)}>Done</a>
      </div>
    );
  }
}

export default Text;
